src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <inlineHelpText>This is the custom field that contains the invoice number for the opportunity.</inlineHelpText>
        <label>Invoice Number</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Vision_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This checkbox should be checked if the opportunity is a vision opportunity.</inlineHelpText>
        <label>Vision Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Vision_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Close_Date__c</fullName>
        <label>Close Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Number__c</fullName>
        <label>Invoice Number</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LeadSource__c</fullName>
        <label>LeadSource</label>
        <picklist>
            <picklistValues>
                <fullName>Web</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Inquiry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage_Name__c</fullName>
        <label>Stage Name</label>
        <picklist>
            <picklistValues>
                <fullName>Prospecting</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Qualification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Needs Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Value Proposition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Id. Decision Makers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perception Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposal/Price Quote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiation/Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Vision_Opportunity_Name__c</fullName>
        <inlineHelpText>This is the name of the vision opportunity.</inlineHelpText>
        <label>Vision Opportunity Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Vision Opportunity</label>
    <nameField>
        <displayFormat>V-{000}</displayFormat>
        <label>Vision Opportunity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vision Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/VisionOpportunityTriggerHelper.cls
//This Class acts as the helper class for the vision opportunity trigger handler.
public class VisionOpportunityTriggerHelper {
    
    //This method copies the record of vision opportunity to opportunity.
    public static Opportunity copyVisionToOpportunity(Vision_Opportunity__c objVisionOpportunity,Opportunity objOpportunity){
    	objOpportunity.Name=objVisionOpportunity.Vision_Opportunity_Name__c;
    	objOpportunity.CloseDate=objVisionOpportunity.Close_Date__c;
    	objOpportunity.Amount=objVisionOpportunity.Amount__c;
    	objOpportunity.StageName=objVisionOpportunity.Stage_Name__c;
    	objOpportunity.LeadSource=objVisionOpportunity.LeadSource__c;
    	objOpportunity.Invoice_Number__c=objVisionOpportunity.Invoice_Number__c;
    	return objOpportunity;
    }
    
    //This method returns a list of opportunities whose stage is not closed won.
    public static List<Opportunity> extractExistingOpportunites(){
    	return [SELECT Id
					 , Name
					 , Invoice_Number__c
					 , StageName
					 , CloseDate
				  FROM Opportunity
				 WHERE Invoice_Number__c!=Null
				   AND StageName!='Closed Won'];
    }
}